# Description: Searches for a string containing a mnemonic.  E.g. "P&lugins" is found by searching for "Plugins".
#
# Input:
#   query         The search phrase
#   folders        The folder filter
#   extensions     The extension filter
#   caseSensitive  Boolean if case sensitive is checked
# Output:
#   result.matches       A list of file names with the matches
#   result.highlight      A regular expression which can be used to search for a match in the files
#   result.label          The label of the search tab
# Functions:
#   performSearch  Call to perform a search in the index

reFlags = 0
if not caseSensitive:
	reFlags = re.IGNORECASE

result.matches.extend (performSearch("class", folders, extensions, caseSensitive))
result.matches.extend (performSearch("public", folders, extensions, caseSensitive))
	
result.highlight = re.compile(regexFromText("class",caseSensitive).pattern+"|"+regexFromText("public",caseSensitive).pattern, reFlags)
result.label = "class+public"
	


	
