# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest
    env:
      PYUIC: pyuic5.exe
      PYRCC5: pyrcc5.exe
      SASS: node_modules\.bin\sass.cmd
      
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 
        pip install Cx_freeze==6.4 PyQt5 pywin32
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.2.0
    - name: Restore NPM packages
      run: npm ci
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Run build
      run: .\buildwindows.bat
    - name: Windows build result
      uses: actions/upload-artifact@v3
      with:
        name: CodeBeagle.Windows
        path: build/CodeBeagle

