name: Windows build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python.exe -m pip install --upgrade pip
        # Cx_freeze was '==6.11' before
        pip install flake8 Cx_freeze PyQt5
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.2.0
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Run build
      run: .\build-windows-freeze.ps1
    - uses: actions/upload-artifact@v4
      name: Windows build result
      with:
        name: CodeBeagle.Windows
        path: build/CodeBeagle

