name: Windows build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      name: Set up Python 3.10
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: pip install flake8 tomlkit Cx_freeze==6.11 PyQt5     
    - uses: actions/setup-node@v3.2.0
      name: Setup Node.js environment
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Run build
      run: .\build-windows-freeze.ps1
    - uses: actions/upload-artifact@v3
      name: Windows build result
      with:
        name: CodeBeagle.Windows
        path: build/CodeBeagle

